period_data : "LHC24apaq"
period_mc : "LHC25b4ab"
pass_number : "pass1"
common:
    system : "pp"
    energy : 5.36 #center-of-mass energy in TeV
    do_mll_ptll: False
    do_mll_ptll_dcall: True
    do_flow: False
    mll_bin: [0, 0.01, 0.02, 0.03, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.24, 0.26, 0.28, 0.3, 0.32, 0.34, 0.36, 0.38, 0.4, 0.42, 0.44, 0.46, 0.48, 0.5,
    0.52, 0.54, 0.56, 0.58, 0.6, 0.62, 0.64, 0.66, 0.68, 0.7, 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8, 0.81,
    0.82, 0.84, 0.86, 0.88, 0.9, 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.98, 0.99, 1.0, 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.08, 1.1,
    1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7,
    2.8, 2.85, 2.9, 2.95, 3.00, 3.05, 3.10, 3.15, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0] # in GeV
    ptll_bin: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.4,1.6, 1.8, 2, 2.5, 3, 3.5, 4, 4.5, 5, 6, 8, 10] #in GeV
    dcall_bin: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 6, 7, 8, 9, 10, 12, 14, 16, 18, 20] #in sigma
    #ptll_bin: [0.0, 10] #in GeV
    #dcall_bin: [0, 999] #in sigma

data:
    tasks:
        - {name: "dielectron_itsib1st", cent_min: 0, cent_max: 999}
        - {name: "dielectron_itsib1st_pi0pfb1", cent_min: 0, cent_max: 999}
        - {name: "dielectron_itsib1st_pi0pfb2", cent_min: 0, cent_max: 999}
        - {name: "dielectron_itsib1st_pi0pfb3", cent_min: 0, cent_max: 999}
        - {name: "dielectron_itsibany", cent_min: 0, cent_max: 999}
        - {name: "dielectron_itsibany_pi0pfb1", cent_min: 0, cent_max: 999}
        - {name: "dielectron_itsibany_pi0pfb2", cent_min: 0, cent_max: 999}
        - {name: "dielectron_itsibany_pi0pfb3", cent_min: 0, cent_max: 999}

        - {name: "dielectron_TOFreq_minpt400", cent_min: 0, cent_max: 999}
        - {name: "dielectron_TPChadrejorTOFreq_minpt200", cent_min: 0, cent_max: 999}
        - {name: "dielectron_TPChadrejorTOFreq_minpt200_wWeighting", cent_min: 0, cent_max: 999}
        - {name: "dielectron_TPChadrejorTOFreq_minpt200_woTTCA", cent_min: 0, cent_max: 999}
        - {name: "dielectron_TPChadrejorTOFreq_minpt200_wophiv", cent_min: 0, cent_max: 999}
        - {name: "dielectron_TPChadrejorTOFreq_minpt200_wpf_mee", cent_min: 0, cent_max: 999}
        - {name: "dielectron_TPChadrejorTOFreq_minpt200_wpf_phiv", cent_min: 0, cent_max: 999}
        - {name: "dielectron_TPChadrejorTOFreq_minpt200_itsibany", cent_min: 0, cent_max: 999}
        - {name: "dielectron_TPChadrejorTOFreq_minpt200_itsibany_wpf_mee", cent_min: 0, cent_max: 999}
        - {name: "dielectron_TPChadrejorTOFreq_minpt200_itsibany_wpf_phiv", cent_min: 0, cent_max: 999}

        - {name: "dielectron_TPChadrejorTOFreq_minpt200_dca3d", cent_min: 0, cent_max: 999}
        - {name: "dielectron_TPChadrejorTOFreq_minpt200_dcaxy", cent_min: 0, cent_max: 999}
        - {name: "dielectron_TPChadrejorTOFreq_minpt200_dcaz", cent_min: 0, cent_max: 999}

        - {name: "dielectron_HM_TPChadrejorTOFreq_minpt200", cent_min: 0, cent_max: 999}
        - {name: "dielectron_HM_TPChadrejorTOFreq_minpt200_wWeighting", cent_min: 0, cent_max: 999}
        - {name: "dielectron_HM_TPChadrejorTOFreq_minpt200_wophiv", cent_min: 0, cent_max: 999}
mc:
    tasks:
        - {name: "dielectron-mc_TOFreq_minpt400", cent_min: 0, cent_max: 999}
        - {name: "dielectron-mc_TPChadrejorTOFreq_minpt200", cent_min: 0, cent_max: 999}
        - {name: "dielectron-mc_TPChadrejorTOFreq_minpt200_wWeighting", cent_min: 0, cent_max: 999}
        - {name: "dielectron-mc_TPChadrejorTOFreq_minpt200_woTTCA", cent_min: 0, cent_max: 999}

