period_data : "LHC23zzh"
period_mc : "LHC24d2b"
pass_number : "pass4"
common:
    system : "PbPb"
    energy : 5.36 #center-of-mass energy in TeV
    do_mll_ptll_dcall: True
    do_flow: False
    do_polarization: False
    mll_bin: [0, 0.02, 0.04, 0.06, 0.08, 0.1, 0.14, 0.3, 0.5, 0.7, 0.9, 1.1, 1.5, 2.0, 2.5, 2.9, 3.0, 3.1, 3.2, 3.5, 4.0] # in GeV
    ptll_bin: [0.0, 0.02, 0.04, 0.06, 0.08, 0.1, 0.15, 0.2, 0.4, 0.6, 0.8, 1.0] #in GeV
    dcall_bin: [0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 3.0, 4.0, 5, 6, 8, 10] #in sigma
data:
    tasks:
        - {name: "dielectron_upc_6080", cent_min: 60, cent_max: 80}
        - {name: "dimuon_upc_standalone_6080", cent_min: 60, cent_max: 80}
mc:
    tasknames:
        - "dielectron-qc-mc_3050"
